### ISSUE TITLE
libnacl should support libsodium 23

### ISSUE THREAD

**Issue by aboe76** [saltstack/libnacl#111]
ibnacl cannot use libsodium.so.23, /libnacl/init.py should be modified to for libsodium.so.23. 
Adding 23 to the __SONAMES array on line 12 should be the simplest fix.

**Comment by dmurphy18** [comment]
@aboe76 It would be helpful to know the version of Salt that you are running, can you run the following and return the results:
salt-run --versions-report

**Comment by aboe76** [comment]
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 3.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 3.6.3
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.17.9-1-default
         system: Linux
        version: Not Installed
 ```

libsodium:
```
rpm -qa|grep libsodium
2885:libsodium23-1.0.16-3.1.x86_64
```
